registry:
  restart: always
  image: chrplace/docker-registry-external-cert
  ports:
    - 443:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/cert.pem
    REGISTRY_HTTP_TLS_KEY: /certs/privkey.pem
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - /srv/docker-reg/data:/var/lib/registry
    - /srv/docker-reg/certs:/certs
    - /srv/docker-reg/auth:/auth
